{
    shop = {
        {text = "Урановая руда", sellPrice = 50, minCount = 0, maxCount = 1310720, fingerprint = {{dmg=0.0,id="IC2:blockOreUran"}, {dmg=0.0,id="minechem:tile.oreUranium"}}, raw_name = {"ic2.blockoreuran", "tile.oreuranium"}},
        {text = "Железная руда", sellPrice = 35, minCount = 0, maxCount = 1310720, fingerprint = {{dmg=0.0,id="minecraft:iron_ore"}}, raw_name = {"tile.oreiron"}},
        {text = "Золотая руда", sellPrice = 45, minCount = 0, maxCount = 1310720, fingerprint = {{dmg=0.0,id="minecraft:gold_ore"}}, raw_name = {"tile.oregold"}},
        {text = "Медная руда", sellPrice = 35, minCount = 0, maxCount = 1310720, fingerprint = {{dmg=0.0,id="ThermalFoundation:Ore"}}, raw_name = {"tile.thermalfoundation.ore.copper.name"}},
        {text = "Оловянная руда", sellPrice = 35, minCount = 0, maxCount = 1310720, fingerprint = {{dmg=1.0,id="ThermalFoundation:Ore"}}, raw_name = {"tile.thermalfoundation.ore.tin.name"}},
        {text = "Серебряная руда", sellPrice = 45, minCount = 0, maxCount = 1310720, fingerprint = {{dmg=2.0,id="ThermalFoundation:Ore"}}, raw_name = {"tile.thermalfoundation.ore.silver.name"}},
        {text = "Никелевая руда", sellPrice = 35, minCount = 0, maxCount = 1310720, fingerprint = {{dmg=4.0,id="ThermalFoundation:Ore"}}, raw_name = {"tile.thermalfoundation.ore.nickel.name"}},
        {text = "Осмиевая руда", sellPrice = 35, minCount = 0, maxCount = 1310720, fingerprint = {{dmg=0.0,id="Mekanism:OreBlock"}}, raw_name = {"tile.oreblock.osmiumore"}},
        {text = "Бокситовая руда", sellPrice = 35, minCount = 0, maxCount = 1310720, fingerprint = {{dmg=1.0,id="ImmersiveEngineering:ore"}}, raw_name = {"tile.immersiveengineering.ore.aluminum"}},
        {text = "Алюминиевая руда", sellPrice = 35, minCount = 0, maxCount = 1310720, fingerprint = {{dmg=5.0,id="TConstruct:SearedBrick"}}, raw_name = {"metalore.aluminum"}},
        {text = "Тритановая руда", sellPrice = 45, minCount = 0, maxCount = 1310720, fingerprint = {{dmg=0.0,id="mo:tritanium_ore"}}, raw_name = {"tile.tritanium_ore"}},

        {text = "Железный слиток", sellPrice = 10, minCount = 1024, maxCount = 1310720, fneeded = 1000, fingerprint = {{dmg=0.0,id="minecraft:iron_ingot"}}, raw_name = {"item.ingotiron"}},
        {text = "Золотой слиток", sellPrice = 15, minCount = 1024, maxCount = 1310720, needed = 1000, fingerprint = {{dmg=0.0,id="minecraft:gold_ingot"}}, raw_name = {"item.ingotgold"}},
        {text = "Серебряный слиток", sellPrice = 10, minCount = 1024, maxCount = 1310720, needed = 1000, fingerprint = {{dmg=6.0,id="IC2:itemIngot", {dmg=66.0,id="ThermalFoundation:material"}}}, raw_name = {"ic2.itemingotsilver", "item.thermalfoundation.material.ingotsilver"}},
        {text = "Медный слиток", sellPrice = 10, minCount = 1024, maxCount = 1310720, needed = 1000, fingerprint = {{dmg=64.0,id="ThermalFoundation:material"}, {dmg=5.0,id="Mekanism:Ingot"}, {dmg=0.0,id="ImmersiveEngineering:metal"}}, raw_name = {"item.thermalfoundation.material.ingotcopper", "item.copperingot", "item.immersiveengineering.metal.ingotcopper"}},
        {text = "Платиновый слиток", sellPrice = 40, minCount = 1024, maxCount = 1310720, needed = 1000, fingerprint = {{dmg=69.0,id="ThermalFoundation:material"}}, raw_name = {"item.thermalfoundation.material.ingotplatinum"}},
        {text = "Осмиевый слиток", sellPrice = 10, minCount = 1024, maxCount = 1310720, needed = 1000, fingerprint = {{dmg=1.0,id="Mekanism:Ingot"}}, raw_name = {"item.osmiumingot"}},
        {text = "Оловянный слиток", sellPrice = 10, minCount = 1024, maxCount = 1310720, needed = 1000, fingerprint = {{dmg=6.0,id="Mekanism:Ingot"}, {id="ThermalFoundation:material",dmg=65.0}, {dmg=1.0,id="IC2:itemIngot"}}, raw_name = {"item.tiningot", "item.thermalfoundation.material.ingottin", "ic2.itemingottin"}},
        {text = "Алюминиевый слиток", sellPrice = 10, minCount = 1024, maxCount = 1310720, needed = 1000, fingerprint = {{dmg=1.0,id="ImmersiveEngineering:metal"}}, raw_name = {"item.immersiveengineering.metal.ingotaluminum"}},
        {text = "Тритановый слиток", sellPrice = 25, minCount = 1024, maxCount = 1310720, fingerprint = {{dmg=0.0,id="mo:tritanium_ingot"}}, raw_name = {"item.tritanium_ingot"}},
        {text = "Свинцовый слиток", sellPrice = 5, minCount = 1024, maxCount = 1310720, needed = 1000, fingerprint = {{dmg=5.0,id="IC2:itemIngot"}}, raw_name = {"ic2.itemingotlead"}},

        {text = "Алмаз", buyPrice = 200, sellPrice = 80, minCount = 2048, maxCount = 1310720, fingerprint = {{dmg=0.0,id="minecraft:diamond"}}, raw_name = {"item.diamond"}},
        {text = "Уголь", buyPrice = 3, sellPrice = 2, minCount = 1024, maxCount = 1310720, needed = 1000, fingerprint = {{dmg=0.0,id="minecraft:coal"}}, raw_name = {"item.coal"}},
        {text = "Кристалл истинного кварца", buyPrice = 7, sellPrice = 5, minCount = 0, maxCount = 1000, needed = 1000, fingerprint = {{dmg=0.0,id="appliedenergistics2:item.ItemMultiMaterial"}}, raw_name = {"item.appliedenergistics2.itemmaterial.certusquartzcrystal"}},
        {text = "Зар. кристалл ист. кварца", buyPrice = 35, minCount = 0, maxCount = 16384, needed = 1000, fingerprint = {{dmg=1.0,id="appliedenergistics2:item.ItemMultiMaterial"}}, raw_name = {"item.appliedenergistics2.itemmaterial.certusquartzcrystalcharged"}},
        {text = "Энергетический кристалл", buyPrice = 750, sellPrice = 80, minCount = 0, maxCount = 16, ignoreDamage = true, fingerprint = {{dmg=27.0,id="IC2:itemBatCrystal"}}, raw_name = {"ic2.itembatcrystal"}},
        {text = "Лазуротроновый кристалл", buyPrice = 950, sellPrice = 90, minCount = 0, maxCount = 16, ignoreDamage = true, fingerprint = {{dmg=26.0,id="IC2:itemBatLamaCrystal"}}, raw_name = {"ic2.itembatlamacrystal"}},
        {text = "Семена Пустотника", buyPrice = 380, minCount = 0, maxCount = 1310720, needed = 1000, fingerprint = {{dmg=0.0,id="thaumicbases:voidSeed"}}, raw_name = {"item.voidseed"}},
        {text = "Семя пустоты", buyPrice = 250, minCount = 0, maxCount = 1310720, needed = 1000, fingerprint = {{dmg=17.0,id="Thaumcraft:ItemResource"}}, raw_name = {"item.itemresource.17"}},
        {text = "Шерсть", buyPrice = 15, minCount = 512, maxCount = 1310720, needed = 1000, fingerprint = {{id="minecraft:wool",dmg=0.0}}, raw_name = {"tile.cloth.white"}},
        {text = "Порох", buyPrice = 30, minCount = 0, maxCount = 1310720, needed = 1000, fingerprint = {{id="minecraft:gunpowder",dmg=0.0}}, raw_name = {"item.sulphur"}},
        {text = "Красная пыль", buyPrice = 4, sellPrice = 2, minCount = 2048, maxCount = 1310720, fingerprint = {{id="minecraft:redstone",dmg=0.0}}, raw_name = {"item.redstone"}},
        {text = "Светопыль", buyPrice = 3, sellPrice = 2, minCount = 1024, maxCount = 1310720, fingerprint = {{id="minecraft:glowstone_dust",dmg=0.0}}, raw_name = {"item.yellowdust"}},
        {text = "Кость", buyPrice = 3, minCount = 0, maxCount = 1310720, needed = 1000, fingerprint = {{id="minecraft:bone",dmg=0.0}}, raw_name = {"item.bone"}},
        {text = "Гнилая плоть", buyPrice = 3, minCount = 0, maxCount = 1310720, needed = 1000, fingerprint = {{id="minecraft:rotten_flesh",dmg=0.0}}, raw_name = {"item.rottenflesh"}},
        {text = "Жемчуг эндера", buyPrice = 30, minCount = 512, maxCount = 1310720, needed = 1000, fingerprint = {{id="minecraft:ender_pearl",dmg=0.0}}, raw_name = {"item.enderpearl"}},
        {text = "Паучий глаз", buyPrice = 25, minCount = 0, maxCount = 1310720, needed = 1000, fingerprint = {{id="minecraft:spider_eye",dmg=0.0}}, raw_name = {"item.spidereye"}},
        {text = "Изумруд", buyPrice = 350, sellPrice = 90, minCount = 512, maxCount = 1024, fingerprint = {{id="minecraft:emerald",dmg=0.0}}, raw_name = {"item.emerald"}},
        {text = "Череп скелета", buyPrice = 150, minCount = 0, maxCount = 512, needed = 1000, fingerprint = {{id="minecraft:skull",dmg=0.0}}, raw_name = {"item.skull.skeleton"}},
        {text = "Голова зомби", buyPrice = 150, minCount = 0, maxCount = 512, needed = 1000, fingerprint = {{id="minecraft:skull",dmg=2.0}}, raw_name = {"item.skull.zombie"}},
        {text = "Голова крипера", buyPrice = 150, minCount = 0, maxCount = 512, needed = 1000, fingerprint = {{id="minecraft:skull",dmg=4.0}}, raw_name = {"item.skull.creeper"}},
        {text = "Голова странника Края", buyPrice = 350, minCount = 0, maxCount = 512, needed = 128, fingerprint = {{id="EnderIO:blockEndermanSkull",dmg=0.0}}, raw_name = {"tile.blockendermanskull.base"}},
        {text = "Выч. пресс для высекателя", buyPrice = 200, sellPrice = 80, minCount = 0, maxCount = 16, fingerprint = {{id="appliedenergistics2:item.ItemMultiMaterial",dmg=13.0}}, raw_name = {"item.appliedenergistics2.itemmaterial.calcprocessorpress"}},
        {text = "Инж. пресс для высекателя", buyPrice = 200, sellPrice = 80, minCount = 0, maxCount = 16, fingerprint = {{id="appliedenergistics2:item.ItemMultiMaterial",dmg=14.0}}, raw_name = {"item.appliedenergistics2.itemmaterial.engprocessorpress"}},
        {text = "Лог. пресс для высекателя", buyPrice = 200, sellPrice = 80, minCount = 0, maxCount = 16, fingerprint = {{id="appliedenergistics2:item.ItemMultiMaterial",dmg=15.0}}, raw_name = {"item.appliedenergistics2.itemmaterial.logicprocessorpress"}},
        {text = "Крем. пресс для высекателя", buyPrice = 200, sellPrice = 80, minCount = 0, maxCount = 16, fingerprint = {{id="appliedenergistics2:item.ItemMultiMaterial",dmg=19.0}}, raw_name = {"item.appliedenergistics2.itemmaterial.siliconpress"}},
        {text = "Сингулярность", buyPrice = 6000, minCount = 0, maxCount = 1310720, fingerprint = {{id="appliedenergistics2:item.ItemMultiMaterial",dmg=47.0}}, raw_name = {"item.appliedenergistics2.itemmaterial.singularity"}},
        {text = "Стальной слиток", buyPrice = 60, minCount = 0, maxCount = 1310720, needed = 128, fingerprint = {{id="ImmersiveEngineering:metal",dmg=7.0}, {dmg=4.0,id="Mekanism:Ingot"}}, raw_name = {"item.immersiveengineering.metal.ingotsteel"}},
        {text = "Маленькое красное сердечко", buyPrice = 850, sellPrice = 30, minCount = 0, maxCount = 128, needed = 1000, fingerprint = {{id="TConstruct:heartCanister",dmg=1.0}}, raw_name = {"item.tconstruct.canister.miniheart.red"}},
        {text = "Сырая резина", buyPrice = 1, minCount = 0, maxCount = 1310720, needed = 1000, fingerprint = {{dmg=0.0,id="MineFactoryReloaded:rubber.raw"}}, raw_name = {"item.mfr.rubber.raw"}},
        {text = "Череп Скелета-Иссушителя", buyPrice = 350, minCount = 0, needed = 128, maxCount = 64, fingerprint = {{dmg=1.0,id="minecraft:skull"}}, raw_name = {"item.skull.wither"}},
        {text = "Укр. иридиевая пластина", buyPrice = 1900, minCount = 0, needed = 16, maxCount = 32, fingerprint = {{id="IC2:itemPartIridium",dmg=0.0}}, raw_name = {"ic2.itempartiridium"}},
        {text = "Кварц", buyPrice = 6, minCount = 1024, maxCount = 2048, needed = 1000, fingerprint = {{dmg=0.0,id="minecraft:quartz"}}, raw_name = {"item.netherquartz"}},
        {text = "Падшая Звезда Ада", buyPrice = 2000, minCount = 0, maxCount = 16384, needed = 16, fingerprint = {{dmg=0.0,id="minecraft:nether_star"}}, raw_name = {"item.netherstar"}},
        {text = "Синаловый слиток", buyPrice = 200, minCount = 0, maxCount = 16384, needed = 128, fingerprint = {{dmg=74.0,id="ThermalFoundation:material"}}, raw_name = {"item.thermalfoundation.material.ingotsignalum"}},
        {text = "Маленькое жёлтое сердечко", buyPrice = 1250, minCount = 0, maxCount = 16384, needed = 16, fingerprint = {{dmg=3.0,id="TConstruct:heartCanister"}}, raw_name = {"item.tconstruct.canister.miniheart.yellow"}},
        {text = "Маленькое зелёное сердечко", buyPrice = 17000, minCount = 0, maxCount = 16384, needed = 1, fingerprint = {{dmg=5.0,id="TConstruct:heartCanister"}}, raw_name = {"item.tconstruct.canister.miniheart.green"}},
        {text = "Флаксовый электрумовый слиток", buyPrice = 200, minCount = 0, maxCount = 16384, needed = 128, fingerprint = {{dmg=32.0,id="RedstoneArsenal:material"}}, raw_name = {"item.redstonearsenal.material.ingotelectrumflux"}},
        {text = "Флаксовый кристалл", buyPrice = 200, minCount = 0, maxCount = 16384, needed = 128, fingerprint = {{dmg=96.0,id="RedstoneArsenal:material"}}, raw_name = {"item.redstonearsenal.material.gemcrystalflux"}},
        {text = "Ускоритель", buyPrice = 550, minCount = 0, needed = 32, maxCount = 16384, fingerprint = {{dmg=0.0,id="IC2:upgradeModule"}}, raw_name = {"ic2.overclockerupgrade"}},
        {text = "Перо", buyPrice = 50, minCount = 0, maxCount = 16384, needed = 1000, fingerprint = {{dmg=0.0,id="minecraft:feather"}}, raw_name = {"item.feather"}},
        {text = "Слиток эндериума", buyPrice = 150, minCount = 0, maxCount = 16384, needed = 128, fingerprint = {{dmg=76.0,id="ThermalFoundation:material"}}, raw_name = {"item.thermalfoundation.material.ingotenderium"}},
        {text = "Стержень ифрита", buyPrice = 5, minCount = 512, maxCount = 1024, needed = 512, fingerprint = {{id="minecraft:blaze_rod",dmg=0.0}}, raw_name = {"item.blazerod"}},
        {text = "Нить", buyPrice = 5, minCount = 0, maxCount = 16384, needed = 512, fingerprint = {{id="minecraft:string",dmg=0.0}}, raw_name = {"item.string"}},
        {text = "Сгусток слизи", buyPrice = 9, minCount = 0, maxCount = 16384, needed = 1000, fingerprint = {{id="minecraft:slime_ball",dmg=0.0}}, raw_name = {"item.slimeball"}},
        {text = "Фрагмент знаний", buyPrice = 60, minCount = 0, maxCount = 16384, needed = 1000, fingerprint = {{id="Thaumcraft:ItemResource",dmg=9.0}}, raw_name = {"item.itemresource.9"}},
        {text = "Багровые ритуалы", buyPrice = 400, minCount = 0, maxCount = 16384, needed = 1000, fingerprint = {{id="Thaumcraft:ItemEldritchObject",dmg=1.0}}, raw_name = {"item.itemeldritchobject.1"}},
        {text = "Литиевая пыль", buyPrice = 35, minCount = 0, maxCount = 16384, needed = 1000, fingerprint = {{id="Mekanism:OtherDust",dmg=4.0}}, raw_name = {"item.lithiumdust"}},
        {text = "Сера", buyPrice = 200, minCount = 0, maxCount = 16384, fingerprint = {{id="ThermalFoundation:material",dmg=16.0}}, raw_name = {"item.thermalfoundation.material.dustsulfur"}},
        {text = "Композит", buyPrice = 150, minCount = 0, maxCount = 16384, needed = 128, fingerprint = {{dmg=0.0,id="IC2:itemPartAlloy"}}, raw_name = {"ic2.itempartalloy"}},
        {text = 'Мобиус "Нестаб./Cтаб." слиток', buyPrice = 700, minCount = 0, maxCount = 16384, needed = 128, fingerprint = {{id="ExtraUtilities:unstableingot",dmg=2.0}}, raw_name = {"item.extrautils:unstableingot.2"}},
        {text = "Нано-сабля", buyPrice = 1500, minCount = 0, maxCount = 16384, ignoreDamage = true, fingerprint = {{dmg=1.0,id="IC2:itemNanoSaber"}}, raw_name = {"ic2.itemnanosaber"}},
        {text = "Нано-шлем", buyPrice = 2000, minCount = 0, maxCount = 16384, ignoreDamage = true, fingerprint = {{dmg=0.0,id="IC2:itemArmorNanoHelmet"}}, raw_name = {"ic2.itemarmornanohelmet"}},
        {text = "Нано-поножи", buyPrice = 1500, minCount = 0, maxCount = 16384, ignoreDamage = true, fingerprint = {{dmg=26.0,id="IC2:itemArmorNanoLegs"}}, raw_name = {"ic2.itemarmornanolegs"}},
        {text = "Нано-ботинки", buyPrice = 1500, minCount = 0, maxCount = 16384, ignoreDamage = true, fingerprint = {{dmg=26.0,id="IC2:itemArmorNanoBoots"}}, raw_name = {"ic2.itemarmornanoboots"}},
        {text = "Квантовый шлем", buyPrice = 17000, minCount = 0, maxCount = 16384, ignoreDamage = true, fingerprint = {{dmg=26.0,id="IC2:itemArmorQuantumHelmet"}}, raw_name = {"ic2.itemarmorquantumhelmet"}},
        {text = "Квантовая кираса", buyPrice = 15000, minCount = 0, maxCount = 16384, ignoreDamage = true, fingerprint = {{dmg=26.0,id="IC2:itemArmorQuantumChestplate"}}, raw_name = {"ic2.itemarmorquantumchestplate"}},
        {text = "Квантовые поножи", buyPrice = 15000, minCount = 0, maxCount = 16384, ignoreDamage = true, fingerprint = {{dmg=26.0,id="IC2:itemArmorQuantumLegs"}}, raw_name = {"ic2.itemarmorquantumlegs"}},
        {text = "Квантовые ботинки", buyPrice = 15000, minCount = 0, maxCount = 16384, ignoreDamage = true, fingerprint = {{dmg=26.0,id="IC2:itemArmorQuantumBoots"}}, raw_name = {"ic2.itemarmorquantumboots"}},
        {text = "Капсула хладагента", buyPrice = 200, minCount = 0, maxCount = 16384, needed = 128, fingerprint = {{dmg=9.0,id="IC2:itemCellEmpty"}}, raw_name = {"ic2.itemcellcoolant"}},
        {text = "Скопление пыльцы", buyPrice = 350, sellPrice = 45, minCount = 0, maxCount = 1310720, fingerprint = {{id="Forestry:pollen",dmg=0.0}}, raw_name = {"item.for.pollen.normal"}},
        {text = "Маточное молочко", buyPrice = 350, sellPrice = 45, minCount = 0, maxCount = 1310720, fingerprint = {{id="Forestry:royalJelly",dmg=0.0}}, raw_name = {"item.for.royaljelly"}},
        {text = "Иридий", buyPrice = 650, minCount = 0, maxCount = 256, needed = 256, fingerprint = {{id="IC2:itemOreIridium",dmg=0.0}}, raw_name = {"ic2.itemoreiridium"}},
        {text = "Улучшенный наножилет", buyPrice = 16000, minCount = 0, maxCount = 16384, ignoreDamage = true, fingerprint = {{dmg=26.0,id="GraviSuite:advNanoChestPlate"}}, raw_name = {"item.advnanochestplate"}},
        {text = "Слеза Гаста", buyPrice = 500, minCount = 0, maxCount = 16384, needed = 64, fingerprint = {{id="minecraft:ghast_tear",dmg=0.0}}, raw_name = {"item.ghasttear"}}
    },

    ore = {
        {text="Железная руда",ratio=3,raw_name={"tile.oreiron"},fingerprint={{dmg=0.0,id="minecraft:iron_ingot"}}},
        {text="Золотая руда",ratio=3,raw_name={"tile.oregold"},fingerprint={{dmg=0.0,id="minecraft:gold_ingot"}}},
        {text="Медная руда",ratio=3,raw_name={"tile.thermalfoundation.ore.copper.name","ic2.blockorecopper"},fingerprint={{dmg=64.0,id="ThermalFoundation:material"},{dmg=0.0,id="IC2:itemIngot"},{dmg=0.0,id="ImmersiveEngineering:metal"},{dmg=5.0,id="Mekanism:Ingot"}}},
        {text="Оловянная руда",ratio=3,raw_name={"tile.thermalfoundation.ore.tin.name","ic2.blockoretin"},fingerprint={{dmg=6.0,id="Mekanism:Ingot"},{dmg=65.0,id="ThermalFoundation:material"},{dmg=1.0,id="IC2:itemIngot"}}},
        {text="Серебряная руда",ratio=3,raw_name={"tile.thermalfoundation.ore.silver.name"},fingerprint={{dmg=66.0,id="ThermalFoundation:material"},{dmg=6.0,id="IC2:itemIngot"}}},
        {text="Осмиевая руда",ratio=3,raw_name={"tile.oreblock.osmiumore"},fingerprint={{dmg=1.0,id="Mekanism:Ingot"}}},
        {text="Свинцовая руда",ratio=3,raw_name={"tile.thermalfoundation.ore.lead.name","ic2.blockorelead"},fingerprint={{dmg=67.0,id="ThermalFoundation:material"},{dmg=5.0,id="IC2:itemIngot"}}}
    },

    food = {{dmg=0.0, id="minecraft:melon"}, {id="minecraft:apple",dmg=0.0}}
}
